### ISSUE TITLE
root works, but not todo example

### ISSUE THREAD

**Issue by gedw99** [neelance/dom#2]
when i go to localhost:8080, it works, and no errors on the bash shell
when i try the path the todo it fails

gedw99-MacBook-Pro:~ apple$ go get -u github.com/gopherjs/gopherjs github.com/neelance/dom
gedw99-MacBook-Pro:~ apple$ gopherjs serve
serving at http://localhost:8080 and on port 8080 of any available addresses
../../usr/local/go/src/time/zoneinfo.go:286:9: undeclared name: loadLocation

go version go1.5beta3 darwin/amd64

**Comment by gedw99** [comment]
i just realised that gophers does not support go 1.5 yet.

so this might be the probem.

**Comment by neelance** [comment]
Yes, that's the reason for this error. Check the `go1.5` branch of the GopherJS project.
